name: 'Helm Deploy'
description: 'Installs/Upgrades a Helm Release'
inputs:
  chart:
    description: 'Name or Path to the chart'
    required: true
  release-name:
    description: 'Name of the release'
    required: true
  sets:
    description: 'A space delimited list of Helm chart sets'
    required: false

runs:
  using: node16
  main: invoke-binary.js
