name: 'CI'
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-kubectl@v1
    - uses: azure/setup-helm@v1
      with:
        version: v3.8.0
    - uses: engineerd/setup-kind@v0.5.0
    - run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
    - uses: ./.
      with:
        release-name: 'test-release'
        chart: 'bitnami/nginx'
